[tool.poetry]
name = "suncal"
version = "0.1.1"
description = ""
authors = ["Franziska Witzel <franziska.witzel@gmail.com>"]

[tool.black]
line-length = 80
skip-string-normalization = true

[tool.isort]
profile = "black"
multi_line_output = 3
force_single_line = true
line_length = 80

[tool.poetry.dependencies]
python = "^3.11.2"
astral = "^2.2"
google-api-python-client = "^1.12.8"
google-auth-httplib2 = "^0.0.4"
google-auth-oauthlib = "^0.4.2"
pydantic = "^1.7.3"
click = "^8.0.1"
rsa = "*"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
black = "^22.3.0"
isort = "^5.8.0"
mypy = "^1.0.0"
ipykernel = "^5.5.0"
jupyter = "^1.0.0"
pylint = "^2.7.4"
types-pytz = "^2022.7.1.0"

[tool.poetry.scripts]
suncal = "suncal.suncal:suncal"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

