[tool.poetry]
name = "suncal"
version = "0.1.4"
description = ""
authors = ["Franziska Witzel <franziska.witzel@gmail.com>"]
[tool.poetry.group.dev.dependencies]
deptry = "^0.8.0"
pylint-pydantic = "^0.1.8"


[tool.black]
line-length = 80
skip-string-normalization = true

[tool.isort]
profile = "black"
multi_line_output = 3
force_single_line = true
line_length = 80

[tool.poetry.dependencies]
python = "^3.11.2"
google-api-python-client = "^1.12.8"
google-auth-oauthlib = "^0.4.2"
pydantic = "^1.7.3"
click = "^8.0.1"
google = "^3.0.0"
pytz = "^2022.7.1"
skyfield = "^1.45"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
black = "==22.12.0"
isort = "^5.8.0"
mypy = "^1.0.0"
ipykernel = "^5.5.0"
jupyter = "^1.0.0"
pylint = "^2.16.2"
types-pytz = "^2022.7.1.0"
types-setuptools = "^67.3.0.1"

[tool.poetry.scripts]
suncal = "suncal.suncal:suncal"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
load-plugins = "pylint_pydantic"

